# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '17.0'
prepare_react_native_project!

# pod 'boost_custom', :podspec => './custom_podspecs/boost.podspec'


# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = FlipperConfiguration.disabled

# Use static frameworks for React Native Firebase compatibility
# This is required for Firebase to work properly with React Native
use_frameworks! :linkage => :static

require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'VaultTemp' do
  config = use_native_modules!
  # pod 'Firebase/Core', :modular_headers => true

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => flipper_config,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'VaultTempTests' do
    inherit! :complete
    # Pods for testing
  end


  # pre_install do |installer|
  #   installer.pod_targets.each do |pod|
  #     if pod.name == 'boost'
  #       pod.instance_variable_set(:@spec, nil)
  #     end
  #   end
  # end

  post_install do |installer|
    # Fix for gRPC module map issue
    require 'fileutils'
    grpc_headers_dir = File.join(installer.sandbox.root, 'Headers/Private/grpc')
    grpc_modulemap_src = File.join(installer.sandbox.root, 'Target Support Files/gRPC-Core/gRPC-Core.modulemap')
    grpc_modulemap_dst = File.join(grpc_headers_dir, 'gRPC-Core.modulemap')
    
    if File.exist?(grpc_modulemap_src)
      FileUtils.mkdir_p(grpc_headers_dir)
      FileUtils.cp(grpc_modulemap_src, grpc_modulemap_dst)
    end
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
        
        # Fix for non-modular header errors with use_frameworks!
        # Allow non-modular includes for React Native and related pods
        if target.name.include?('React') || target.name.include?('RCT') || target.name.include?('react-native')
          config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
          # Add ReactCommon header search paths for bridging and other headers
          react_native_path = File.join(__dir__, '..', 'node_modules', 'react-native')
          react_native_abs = File.expand_path(react_native_path)
          if Dir.exist?(react_native_abs)
            config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
            config.build_settings['HEADER_SEARCH_PATHS'] << File.join(react_native_abs, 'ReactCommon')
          end
        end
        
        # Fix for react-native-image-picker
        if target.name == 'react-native-image-picker'
          config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        end
        
        # Fix for react-native-vision-camera
        if target.name == 'VisionCamera'
          config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
          config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
          # Add header search paths for React Native headers including bridging
          react_native_path = File.join(__dir__, '..', 'node_modules', 'react-native')
          react_native_abs = File.expand_path(react_native_path)
          if Dir.exist?(react_native_abs)
            config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
            # Add ReactCommon root for bridging headers (react/bridging/...)
            config.build_settings['HEADER_SEARCH_PATHS'] << File.join(react_native_abs, 'ReactCommon')
            config.build_settings['HEADER_SEARCH_PATHS'] << File.join(react_native_abs, 'ReactCommon', 'react', 'nativemodule', 'core', 'platform', 'ios')
            config.build_settings['HEADER_SEARCH_PATHS'] << File.join(react_native_abs, 'React')
          end
        end
        
        # Fix for abseil (Firebase/gRPC dependency)
        if target.name == 'abseil'
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
          config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
          config.build_settings['GCC_C_LANGUAGE_STANDARD'] = 'c11'
          config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
        end
        
        # Fix for gRPC and related C++ libraries
        if target.name.include?('gRPC') || target.name.include?('BoringSSL-GRPC') || target.name.include?('leveldb')
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
          config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
          config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
        end
        
        # Fix for Firebase Swift compatibility
        if target.name.include?('Firebase') || target.name.include?('RNFB')
          config.build_settings['SWIFT_VERSION'] = '5.0'
          config.build_settings['DEFINES_MODULE'] = 'YES'
        end
        
        # Fix for react-native-worklets-core
        if target.name == 'react-native-worklets-core'
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
          config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
          config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
          config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
          # Add header search paths for React Native headers
          react_native_path = File.join(__dir__, '..', 'node_modules', 'react-native')
          # Convert to absolute path and ensure it exists
          react_native_abs = File.expand_path(react_native_path)
          if Dir.exist?(react_native_abs)
            config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
            # The ReactCommon headers are at: ReactCommon/react/nativemodule/core/platform/ios/ReactCommon/
            # Import is: <ReactCommon/RCTTurboModule.h>
            # So we need the parent of the ReactCommon directory
            common_path = File.join(react_native_abs, 'ReactCommon', 'react', 'nativemodule', 'core', 'platform', 'ios')
            if Dir.exist?(common_path)
              config.build_settings['HEADER_SEARCH_PATHS'] << common_path
            end
            # Also add React and ReactCommon root
            config.build_settings['HEADER_SEARCH_PATHS'] << File.join(react_native_abs, 'React')
            config.build_settings['HEADER_SEARCH_PATHS'] << File.join(react_native_abs, 'ReactCommon')
          end
        end
      end
    end
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
      if target.name == 'RNScreens'
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        end  
      end
    end

  end
end

