# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.0'
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = FlipperConfiguration.disabled

# Use static frameworks for React Native Firebase compatibility
# This is required for Firebase to work properly with React Native
use_frameworks! :linkage => :static

target 'VaultTemp' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'VaultTempTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # Fix for gRPC module map issue
    require 'fileutils'
    grpc_headers_dir = File.join(installer.sandbox.root, 'Headers/Private/grpc')
    grpc_modulemap_src = File.join(installer.sandbox.root, 'Target Support Files/gRPC-Core/gRPC-Core.modulemap')
    grpc_modulemap_dst = File.join(grpc_headers_dir, 'gRPC-Core.modulemap')
    
    if File.exist?(grpc_modulemap_src)
      FileUtils.mkdir_p(grpc_headers_dir)
      FileUtils.cp(grpc_modulemap_src, grpc_modulemap_dst)
    end
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        
        # Fix for non-modular header errors with use_frameworks!
        # Allow non-modular includes for React Native and related pods
        if target.name.include?('React') || target.name.include?('RCT') || target.name.include?('react-native')
          config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        end
        
        # Fix for react-native-image-picker
        if target.name == 'react-native-image-picker'
          config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        end
        
        # Fix for Firebase Swift compatibility
        if target.name.include?('Firebase') || target.name.include?('RNFB')
          config.build_settings['SWIFT_VERSION'] = '5.0'
          config.build_settings['DEFINES_MODULE'] = 'YES'
        end
      end
    end
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
